/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2016-04-23 07:18:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fnew_005finvigilator_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Admin</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"img/favicon.ico\" />\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    <script src=\"js/prototype.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/events.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/tabs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("\t <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_reset.css\" media=\"all\"></link>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_boxes.css\" media=\"all\"></link>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_menu.css\" media=\"screen, projection\"></link>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"html-body\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("       \r\n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "admin_header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("        \t\t<div class=\"middle\" id=\"anchor-content\">\r\n");
      out.write("            <div id=\"page:main-container\">\r\n");
      out.write("\t\t\t\t<div class=\"columns \">\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t\t<div class=\"\" id=\"page:left\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                        <ul id=\"isoft\" class=\"tabs\">\r\n");
      out.write("    \t\t\t\t\t                        \r\n");
      out.write("                            \r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("                               \r\n");
      out.write("                                <div id=\"isoft_group_4_content1\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"entry-edit\">\r\n");
      out.write("                                        <div class=\"entry-edit-head\">\r\n");
      out.write("                                            <h4 class=\"icon-head head-edit-form fieldset-legend\">New invigilator</h4>\r\n");
      out.write("                                            <div class=\"form-buttons\">\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                    \t</div>\r\n");
      out.write("\r\n");
      out.write("                                        <fieldset id=\"group_fields4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                            <div class=\"hor-scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form action=\"InvigilatorAction\" method=\"post\">\r\n");
      out.write("                                                <table cellspacing=\"0\" class=\"form-list\">\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"hidden\">\r\n");
      out.write("                                                      <td class=\"label\"><label >Invigilator ID</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  <td class=\"value\">\r\n");
      out.write("                                                        \t<input id=\"\" name=\"invgid\" value=\"\" class=\" input-text\" type=\"text\"/>\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        <td><small></small></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"hidden\">\r\n");
      out.write("                                                      <td class=\"label\"><label >Class room</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  <td class=\"value\">\r\n");
      out.write("                                                        \t<input id=\"\" name=\"invgcls\" value=\"\" class=\" input-text\" type=\"text\"/>\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        <td><small></small></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"hidden\">\r\n");
      out.write("                                                      <td class=\"label\"><label >Time</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  <td class=\"value\">\r\n");
      out.write("                                                        \t<input id=\"\" name=\"time\" value=\"\" class=\" input-text\" type=\"text\"/>\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        <td><small></small></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"hidden\">\r\n");
      out.write("                                                      <td class=\"label\"><label >Invigilator Name</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  <td class=\"value\">\r\n");
      out.write("                                                        \t<input id=\"\" name=\"invgname\" value=\"\" class=\" input-text\" type=\"text\"/>\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        <td><small></small></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"hidden\">\r\n");
      out.write("                                                      <td class=\"label\"><label >Password</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  <td class=\"value\">\r\n");
      out.write("                                                        \t<input id=\"\" name=\"invgpass\" value=\"\" class=\" input-text\" type=\"text\"/>\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        <td><small></small></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table style=\"text-align:center;margin:30px  0 50px 250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr >\r\n");
      out.write("                                                     \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  <td >\r\n");
      out.write("                                                        \t<input id=\"\" name=\"\" value=\"Submit\"  type=\"submit\"/>\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        \r\n");
      out.write("                                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("                            isoftJsTabs = new varienTabs('isoft', 'main_form', 'isoft_group_4', []);\r\n");
      out.write("                        </script>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<div class=\"main-col\" id=\"content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main-col-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"messages\">\r\n");
      out.write("                             </div>\r\n");
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("                            \r\n");
      out.write("                            <form action=\"#\" method=\"post\" id=\"main_form\" name=\"main_form\" enctype=\"multipart/form-data\">\r\n");
      out.write("                            \t<input type=\"hidden\" id=\"submitform\" name=\"submitform\" value=\"1\" >\r\n");
      out.write("                            \t<div style=\"display:none\"></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("        </div>\t\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
