/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2016-04-25 04:55:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class invigilator_005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" <div class=\"header\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"header-top\">\r\n");
      out.write("    \t\t\t<a href=\"invigilator_home.jsp\"><img src=\"img/Logo.png\" alt=\"Logo\" class=\"logo\"/></a>\r\n");
      out.write("    \t\t\t<div class=\"header-right\">\r\n");
      out.write("                    <p class=\"super\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                        Logged in as user&#160;&#160;<font color=\"#4C9AC8;\">Auditor name</font><span class=\"separator\">|</span>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"LogoutAction\" class=\"link-logout\">Log Out</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("            \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            \r\n");
      out.write("        \t<div class=\"clear\"></div>\r\n");
      out.write("\t\r\n");
      out.write("            <div class=\"nav-bar\" >\r\n");
      out.write("            \t<ul id=\"nav\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                \t\r\n");
      out.write("                   <!-- <li onmouseover=\"Element.addClassName(this,'over')\" onmouseout=\"Element.removeClassName(this,'over')\"  class=\"  parent level0\"> <a href=\"#\" onclick=\"return false\"><span><b>Add new apps</b></span></a>\r\n");
      out.write("                    \t<ul >\r\n");
      out.write("                    \t\t<li class=\"level1\"> <a href=\"data_center_new.jsp\" class=\"\"><span>New Date Centre</span></a></li>\r\n");
      out.write("                            <li  class=\"level1\"> <a href=\"data_center_view.jsp\" class=\"\"><span>View Date Centre</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>-->\r\n");
      out.write("\t\t\t\t\t <li   class=\"  parent level0\"> <a href=\"invigilator_home.jsp\" ><span><b>Home</b></span></a> </li>\r\n");
      out.write("                    <li   class=\"  parent level0\"> <a href=\"ViewInvgExamnationSch\" ><span><b>View Invigilator Schedule</b></span></a> </li>\r\n");
      out.write("\t\t\t\t\t<li   class=\"  parent level0\"> <a href=\"ViewInvigilatorStatusAction\" ><span><b>Status</b></span></a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                   \r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
