/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2016-04-25 04:41:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>user home</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"img/favicon.ico\" />\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    <script src=\"js/prototype.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/events.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/tabs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("\t <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_reset.css\" media=\"all\"></link>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_boxes.css\" media=\"all\"></link>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_menu.css\" media=\"screen, projection\"></link>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"html-body\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("       \r\n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "user_header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"middle\" id=\"anchor-content\">\r\n");
      out.write("            <div id=\"page:main-container\">\r\n");
      out.write("\t\t\t\t<div class=\"columns \">\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t\t<div class=\"\" id=\"page:left\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                        <ul id=\"isoft\" class=\"tabs\">\r\n");
      out.write("    \t\t\t\t\t                        \r\n");
      out.write("                            \r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("                               \r\n");
      out.write("                                <div id=\"isoft_group_4_content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<marquee >\r\n");
      out.write("<span style=\"font-size:30px;color:#EC6E07;padding-top:20px;\">Automation Of Examination System</span>\r\n");
      out.write("</marquee >\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" style=\"margin-left:-40px;margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img border=\"0\" alt=\"AOES\" src=\"img/online_exam.jpg\" width=\"400\" height=\"320\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <p style=\"font-size:40px;color:#CF2118;padding-top:20px;margin-left:60px;line-height:50px;\">Automation Of Examination System</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("                            isoftJsTabs = new varienTabs('isoft', 'main_form', 'isoft_group_4', []);\r\n");
      out.write("                        </script>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<div class=\"main-col\" id=\"content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main-col-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"messages\">\r\n");
      out.write("                             </div>\r\n");
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("                            \r\n");
      out.write("                            <form action=\"#\" method=\"post\" id=\"main_form\" name=\"main_form\" enctype=\"multipart/form-data\">\r\n");
      out.write("                            \t<input type=\"hidden\" id=\"submitform\" name=\"submitform\" value=\"1\" >\r\n");
      out.write("                            \t<div style=\"display:none\"></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("        </div>\t\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
