/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2016-04-25 04:41:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import com.auto.bean.*;
import javax.servlet.http.HttpSession;

public final class view_005fexam_005fschedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Admin</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"img/favicon.ico\" />\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    <script src=\"js/prototype.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/events.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/tabs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("\t <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_reset.css\" media=\"all\"></link>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_boxes.css\" media=\"all\"></link>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/admin_menu.css\" media=\"screen, projection\"></link>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"html-body\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("       \r\n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "user_header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("        \t\t<div class=\"middle\" id=\"anchor-content\">\r\n");
      out.write("            <div id=\"page:main-container\">\r\n");
      out.write("\t\t\t\t<div class=\"columns \">\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t\t<div class=\"\" id=\"page:left\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                        <ul id=\"isoft\" class=\"tabs\">\r\n");
      out.write("    \t\t\t\t\t                        \r\n");
      out.write("                            \r\n");
      out.write("\t\t\t\t\t\t<li >\r\n");
      out.write("                               \r\n");
      out.write("                                <div id=\"isoft_group_4_content1\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"entry-edit\">\r\n");
      out.write("                                        <div class=\"entry-edit-head\">\r\n");
      out.write("                                            <h4 class=\"icon-head head-edit-form fieldset-legend\">view Exam Schedule</h4>\r\n");
      out.write("                                           \r\n");
      out.write("                                    \t</div>\r\n");
      out.write("\r\n");
      out.write("                                        <div>\r\n");
      out.write("        \t\t\t<div id=\"customerGrid\">\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"hor-scroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<table cellspacing=\"0\" class=\"data\" id=\"customerGrid_table\">\r\n");
      out.write("                                <col  width=\"50\"  width=\"100px\"  />\r\n");
      out.write("                                <col  width=\"150\"  />\r\n");
      out.write("\t\t\t\t\t\t\t\t<col  width=\"150\"  />\r\n");
      out.write("                               \r\n");
      out.write("                               <thead>\r\n");
      out.write("\t\t\t\t\t\t\t   \r\n");
      out.write("\t            \t                <tr class=\"headings\">\r\n");
      out.write("                                        <th >Subject</th>\r\n");
      out.write("                                        <th >Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th >Duration</th>\r\n");
      out.write("                                       \r\n");
      out.write("\t                \t            </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t    \t    \t    \t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
  

								ArrayList arrayList = (ArrayList)request.getAttribute("exmlist");
								if(arrayList!=null){
								for(Iterator iter = arrayList.iterator(); iter.hasNext();) {
						   ExaminationTO ex = (ExaminationTO) iter.next();
						   
						  
						   
      out.write("\r\n");
      out.write("                                <tr id=\"\" >\r\n");
      out.write("                                        <td >");
      out.print(ex.getSubject());
      out.write("</td>\r\n");
      out.write("                                        <td class=\" \">");
      out.print(ex.getDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\" \">");
      out.print(ex.getDuration());
      out.write("</td>\r\n");
      out.write("                                   </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t   ");
}}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("                            isoftJsTabs = new varienTabs('isoft', 'main_form', 'isoft_group_4', []);\r\n");
      out.write("                        </script>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<div class=\"main-col\" id=\"content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main-col-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"messages\">\r\n");
      out.write("                             </div>\r\n");
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("                            \r\n");
      out.write("                            <form action=\"#\" method=\"post\" id=\"main_form\" name=\"main_form\" enctype=\"multipart/form-data\">\r\n");
      out.write("                            \t<input type=\"hidden\" id=\"submitform\" name=\"submitform\" value=\"1\" >\r\n");
      out.write("                            \t<div style=\"display:none\"></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("        </div>\t\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
